// Generated by CoffeeScript 1.10.0

/*
  Replace patterns on responce

  patterns = 
    'regString': 'file'
 */

(function() {
  var patterns;

  patterns = {
    '/api/directories/doctors/schedule\\?date=30.09.2016': 'store/doctors.30.09.json',
    '/api/directories/doctors/schedule\\?date=29.09.2016': 'store/doctors.29.09.json',
    'none/': ''
  };

  exports.getPaterns = function() {
    return patterns;
  };

  exports.setPattern = function(key, params) {
    return patterns[key] = params;
  };

  exports.deletePattern = function(key) {
    return delete patterns[key];
  };

}).call(this);
