// Generated by CoffeeScript 1.10.0

/*
  Example use server node-fiddler
 */

(function() {
  var $port, $portStatic, _prev, arg, i, nodeFiddler, options, ref;

  nodeFiddler = require('./server');


  /*
    request -> proxy req
   */

  $portStatic = 8080;

  options = {
    ws: true,
    router: {
      "localhost/api": "localhost:" + $portStatic + "/api",
      "localhost/ws": "localhost:" + $portStatic + "/ws",
      "localhost/assets": "localhost:" + $portStatic + "/assets",
      "localhost/plugins": "localhost:" + $portStatic + "/plugins",
      "localhost/index": "localhost:" + $portStatic + "/index",
      "localhost/isLogin": "localhost:" + $portStatic + "/isLogin",
      "localhost/login": "localhost:" + $portStatic + "/login",
      "localhost/logout": "localhost:" + $portStatic + "/logout",
      "localhost/": "localhost:3000/"
    }
  };

  $port = void 0;

  ref = process.argv;
  for (i = ref.length - 1; i >= 0; i += -1) {
    arg = ref[i];
    if (arg === '-p') {
      $port = _prev;
    }
    _prev = arg;
  }

  nodeFiddler.run(options, "", $port, $portStatic);

}).call(this);
